import{a as L,i,S as w}from"./assets/vendor-DDdXnYQq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();async function d(r,t=1){try{const o=await L.get("https://pixabay.com/api/",{params:{key:"51402348-a0c5f352e8dacc54a34bc803e",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return o.data.hits.length===0&&i.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"}),{hits:o.data.hits,totalHits:o.data.totalHits}}catch(o){throw o}}let b=new w(".gallery a");function u(r){const t=document.querySelector(".gallery"),o=r.map(l=>{const{webformatURL:e,largeImageURL:s,tags:a,likes:g,views:h,comments:y,downloads:v}=l;return`<li class="img-li">
        <a href="${s}">
        <img src="${e}" alt="${a}" class="img">
        <div class="all-stats">
        <div class="stats"><p class="stats-name">Likes</p><p class="stats-value">${g}</p></div>
        <div class="stats"><p class="stats-name">Views</p><p class="stats-value">${h}</p></div>
        <div class="stats"><p class="stats-name">Comments</p><p class="stats-value">${y}</p></div>
        <div class="stats"><p class="stats-name">Downloads</p><p class="stats-value">${v}</p></div>
        </div>
        </a>
        </li>`}).join("");t.insertAdjacentHTML("beforeend",o),b.refresh()}function S(){document.querySelector(".gallery").innerHTML=""}function m(){document.querySelector(".loader").classList.remove("visually-hidden")}function f(){document.querySelector(".loader").classList.add("visually-hidden")}function q(){document.querySelector(".load-more").classList.remove("visually-hidden")}function p(){document.querySelector(".load-more").classList.add("visually-hidden")}const C=document.querySelector(".form");let n=1,c;document.querySelector(".load-more").addEventListener("click",E);async function E(r){r.preventDefault(),m(),n+=1;try{const t=await d(c,n);u(t.hits);const o=document.querySelector(".img-li").getBoundingClientRect().height*2;window.scrollBy({top:o,behavior:"smooth"}),(t.hits.length<15||n*15===t.totalHits)&&(p(),i.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"}));return}catch{i.show({message:"Error happened",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"});return}finally{f()}}C.addEventListener("submit",async r=>{if(r.preventDefault(),p(),c=r.currentTarget.elements["search-text"].value.trim(),!c){i.show({message:"Please fill in the field",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"});return}m(),S(),n=1;try{const t=await d(c);return t.totalHits>15&&q(),u(t.hits)}catch{i.show({message:"Error happened",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"});return}finally{f()}});
//# sourceMappingURL=index.js.map
