import{a as L,i,S as w}from"./assets/vendor-DDdXnYQq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();async function d(o,t=1){try{const r=await L.get("https://pixabay.com/api/",{params:{key:"51402348-a0c5f352e8dacc54a34bc803e",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return r.data.hits.length===0&&i.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"}),r.data.hits}catch(r){throw r}}let b=new w(".gallery a");function u(o){const t=document.querySelector(".gallery"),r=o.map(n=>{const{webformatURL:e,largeImageURL:s,tags:a,likes:g,views:h,comments:y,downloads:v}=n;return`<li class="img-li">
        <a href="${s}">
        <img src="${e}" alt="${a}" class="img">
        <div class="all-stats">
        <div class="stats"><p class="stats-name">Likes</p><p class="stats-value">${g}</p></div>
        <div class="stats"><p class="stats-name">Views</p><p class="stats-value">${h}</p></div>
        <div class="stats"><p class="stats-name">Comments</p><p class="stats-value">${y}</p></div>
        <div class="stats"><p class="stats-name">Downloads</p><p class="stats-value">${v}</p></div>
        </div>
        </a>
        </li>`}).join("");t.insertAdjacentHTML("beforeend",r),b.refresh()}function S(){document.querySelector(".gallery").innerHTML=""}function m(){document.querySelector(".loader").classList.remove("visually-hidden")}function f(){document.querySelector(".loader").classList.add("visually-hidden")}function q(){document.querySelector(".load-more").classList.remove("visually-hidden")}function p(){document.querySelector(".load-more").classList.add("visually-hidden")}const C=document.querySelector(".form");let c=1,l;document.querySelector(".load-more").addEventListener("click",E);async function E(o){o.preventDefault(),m(),c+=1;try{const t=await d(l,c);f(),u(t);const r=document.querySelector(".img-li").getBoundingClientRect().height*2;window.scrollBy({top:r,behavior:"smooth"}),t.length<15&&(p(),i.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"}));return}catch{i.show({message:"Error happened",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"});return}}C.addEventListener("submit",async o=>{if(o.preventDefault(),p(),l=o.currentTarget.elements["search-text"].value.trim(),!l){i.show({message:"Please fill in the field",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"});return}m(),S();try{const t=await d(l);return t.length>=15&&q(),c=1,u(t)}catch{i.show({message:"Error happened",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"});return}finally{f()}});
//# sourceMappingURL=index.js.map
